### ISSUE TITLE
Trying to add a buttom prop for the script

### ISSUE THREAD

**Issue by StableBarcodeDev** [BryanLTU/bryan_paintjob#2]
my problem is an error when trying to add a prop spawning in the location of control.

my new config looks like:

`lua

Config = {}

Config.UseTarget = true

Config.Locations = {
    {
        control = { pos = vector4(-197.92, -1332.84, 32.04, 93.32), rotation = vector3(0, 0, 0) },
        vehicle = vector3(-194.72, -1327.0,  31.13),
        sprays = {
            { pos = vector3(-190.76, -1325.08, 31.32), rotation = vector3(0, 25, 180), scale = 1.2 },
            { pos = vector3(-190.84, -1328.16, 31.32), rotation = vector3(0, 25, 180), scale = 1.2 },
            { pos = vector3(-192.36, -1331.08, 31.32), rotation = vector3(0, 25, 90), scale = 1.2 },
            { pos = vector3(-194.04, -1331.12, 31.32), rotation = vector3(0, 25, 90), scale = 1.2 },
            { pos = vector3(-195.72, -1322.92, 31.32), rotation = vector3(0, 25, -90), scale = 1.2 },
            { pos = vector3(-193.4, -1322.92, 31.32), rotation = vector3(0, 25, -90), scale = 1.2 },
        },
        jobs = {'bennys'}, -- false
    },
}

Config.SprayModel = 'prop_tool_nailgun'
Config.ButtonModel = 'v_ilev_chopshopswitch'
`

and the client looks like 

`InitializePaint = function(pos)
    local v = Config.Locations[pos]

    local hash = GetHashKey(Config.ButtonModel)
    while not HasModelLoaded(hash) do
        RequestModel(hash)
        Citizen.Wait(10)
    end

    local object = CreateObject(hash, v.control.pos.x, v.control.pos.y, v.control.pos.z, false, true, false)
    FreezeEntityPosition(object, true)
    PlaceObjectOnGroundProperly(object)

    -- Check if the 'rotation' field exists in the location table
    if v.control.rotation then
        SetEntityRotation(object, v.control.rotation.x, v.control.rotation.y, v.control.rotation.z, 0, 1)
    end

    table.insert(colorButtom, {
        object = object,
        id = id,
        location = k,
    })

    -- The rest of your code...

end
`

and i am getting that error 
![Screenshot_7](https://github.com/BryanLTU/bryan_paintjob/assets/92280829/3230054b-c85c-4e09-9a0f-e76b30609ee6)

**Comment by BryanLTU** [comment]
Hello. What you're trying to do I believe is okay. But You forgot to change the target's coordinates. That's the reason why it's printing that error. You should change it at `client.lua line:29` (attached image)
![image](https://github.com/BryanLTU/bryan_paintjob/assets/60313619/b12e851c-d535-477b-abe4-c9fdeed9ebb1)

**Comment by StableBarcodeDev** [comment]
Do you have any idea of what i have to do to fix that? i am gonna made full changes to the script. like adding a gas mask and if player don't wear that they will lose health and more thinks like that.  i am breaking my head trying to add the button xD

**Comment by BryanLTU** [comment]
Well in Your case instead of Target doing like:
 `coords =  v.control`

You should do something like this:
`coords = v.control.pos`

**Comment by StableBarcodeDev** [comment]
yes that seems to work at some point, but i came into over errors, anyway thanks for i help i will figured it out and i will let you know when i am done

**Comment by BryanLTU** [comment]
Good to hear. Hope I can help in the future :)
