### ISSUE TITLE
client error when painting starts

### ISSUE THREAD

**Issue by Taylor-McGaw-Skyline-DEV** [BryanLTU/bryan_paintjob#3]
![image](https://github.com/BryanLTU/bryan_paintjob/assets/28567929/864fda03-fe1e-444e-b527-f5db0e2b19ba)

**Comment by Salto4501** [comment]
Same Error on my side ! [](url)
![sdsds](https://github.com/BryanLTU/bryan_paintjob/assets/52041293/e46f99f7-be57-4037-b2da-ca1d3395db0d)

**Comment by BryanLTU** [comment]
My apologies, will fix it today or tomorrow.

**Comment by Taylor-McGaw-Skyline-DEV** [comment]
i did fix it just added
 `if r == nil then
    r = 0
end
if g == nil then
    g = 0
end
if b == nil then
    b = 0
end`

**Comment by Taylor-McGaw-Skyline-DEV** [comment]
![image](https://github.com/BryanLTU/bryan_paintjob/assets/28567929/443a2f5a-26cf-451d-ac48-18e31deba76d)

**Comment by BryanLTU** [comment]
Not quite exactly, but similar. I can't fix it because currently I'm on vacation.

**Comment by BryanLTU** [comment]
Fixed in the latest commit. Thanks for bringing up this issue!
